import Config

config :matrix, :trace, System.get_env("EL_TRACE")
config :elita, :registrations, System.get_env("AGENT_REGISTRATIONS")
config :elita, :run, System.get_env("ELITA_RUN", "")
config :elita, :mlm_host, System.get_env("MLM_HOST", "localhost")
config :elita, :mlm_model, System.get_env("MLM_MODEL", "qwen3-fast")
config :elita, :llm, System.get_env("LLM", "lite")
config :elita, :claude_model, System.get_env("CLAUDE_MODEL", "haiku")
config :elita, :base_url, System.get_env("ANTHROPIC_BASE_URL", "https://api.anthropic.com")
config :elita, :auth_token, System.get_env("ANTHROPIC_AUTH_TOKEN") || System.get_env("ANTHROPIC_API_KEY")
config :elita, :ca_certs, System.get_env("NODE_EXTRA_CA_CERTS")
config :elita, :tape_on_miss, System.get_env("TAPE_ON_MISS")
config :elita, :clock_override, System.get_env("CLOCK")
config :el, :claude, System.get_env("CLAUDE")
config :el, :system_prompt, System.get_env("EL_SYSTEM_PROMPT")
config :el, :claude_model, System.get_env("CLAUDE_MODEL", "haiku")
config :el, :from, System.get_env("EL_FROM")
config :el, :rows, System.get_env("EL_ROWS")
config :el, :cols, System.get_env("EL_COLS")
config :el, :node_spawn, System.get_env("EL_NODE_SPAWN")
config :el, :runner, System.get_env("TEST_AGENT_RUNNER")
config :el, :puppet, System.get_env("PUPPET_NAME")
