require_relative 'styles'

module Template
  def self.render(grouped, total, count, zeros, dropped)
    "#{build_header(total, count, zeros, dropped)}#{build_grouped_rows(grouped)}#{build_footer}"
  end

  def self.build_header(total, count, zeros, dropped)
    color = color_for(total)
    total_fmt = format('%.2f', total)
    <<~HTML
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Coverage Report</title>
        <style>#{Styles::RULES}</style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>Coverage Report</h1>
            <div class="summary-row">
              #{summary_tiles(color, total_fmt, count, zeros, dropped)}
            </div>
          </div>
          <div class="content">
            <div class="controls">
              <button onclick="expandAll()">Expand All</button>
              <button onclick="collapseAll()">Collapse All</button>
            </div>
            <div class="groups">
    HTML
  end

  def self.summary_tiles(color, total_fmt, count, zeros, dropped)
    <<~HTML
      <div class="summary-item">
        <div class="summary-label">Total Coverage</div>
        <div class="summary-value" style="background-color: ##{color};">#{total_fmt}%</div>
      </div>
      <div class="summary-item">
        <div class="summary-label">Modules (with pages)</div>
        <div class="summary-count">#{count}</div>
      </div>
      <div class="summary-item">
        <div class="summary-label">No Coverage</div>
        <div class="summary-count" style="color: #e05d44;">#{zeros}</div>
      </div>
      <div class="summary-item">
        <div class="summary-label">Dropped (no pages)</div>
        <div class="summary-count" style="color: #999;">#{dropped}</div>
      </div>
    HTML
  end

  def self.build_grouped_rows(grouped)
    rows_html = grouped.map { |folder, modules| build_group(folder, modules) }.join
    "#{rows_html}\n            </div>"
  end

  def self.build_group(folder, modules)
    avg_pct = compute_avg(modules)
    summary_html = build_group_summary(folder, avg_pct)
    modules_html = build_module_rows(modules)
    "<details>\n  #{summary_html}\n  #{modules_html}</details>\n"
  end

  def self.compute_avg(modules)
    modules.map { |m| m[:pct] }.sum.to_f / modules.length
  end

  def self.build_module_rows(modules)
    rows = modules.map { |m| build_module_row(m) }.join
    "<table class=\"modules-table\">\n    <tbody>\n#{rows}    </tbody>\n  </table>\n"
  end

  def self.build_group_summary(folder, avg_pct)
    color = color_for(avg_pct)
    avg_fmt = format('%.2f', avg_pct)
    bar_text = bar_text_for(avg_pct)

    <<~HTML
      <summary>
        <span class="group-folder">#{folder}</span>
        <span class="pct-cell" style="background-color: ##{color}; border-radius: 4px;">#{avg_fmt}%</span>
        <div class="bar-cell">
          <div class="bar-container">
            <div class="bar-fill" style="width: #{avg_pct}%; background-color: ##{color};">
              #{bar_text}
            </div>
          </div>
        </div>
      </summary>
    HTML
  end

  def self.build_module_row(data)
    name = data[:name]
    pct = data[:pct]
    color = color_for(pct)
    pct_fmt = format('%.2f', pct)
    bar_text = bar_text_for(pct)
    <<~HTML
      <tr>
        <td><a href="Elixir.#{name}.html" class="module-name">#{name}</a></td>
        <td class="pct-cell" style="background-color: ##{color}; border-radius: 4px;">#{pct_fmt}%</td>
        <td class="bar-cell">
          <div class="bar-container">
            <div class="bar-fill" style="width: #{pct}%; background-color: ##{color};">
              #{bar_text}
            </div>
          </div>
        </td>
      </tr>
    HTML
  end

  def self.bar_text_for(pct)
    pct.zero? ? '' : format('%.1f', pct)
  end

  def self.build_footer
    <<~HTML
      </div>
            <div class="footer">
              Coverage report generated by mix cover
            </div>
          </div>
        </body>
        <script>
          function expandAll() {
            document.querySelectorAll('details').forEach(d => d.open = true);
          }
          function collapseAll() {
            document.querySelectorAll('details').forEach(d => d.open = false);
          }
        </script>
      </html>
    HTML
  end

  def self.color_for(pct)
    pct >= 80.0 ? '23D96C' : high_or_low(pct)
  end

  def self.high_or_low(pct)
    pct >= 50.0 ? 'dfb317' : 'e05d44'
  end
end
