require_relative 'styles'
require_relative 'client'
require 'json'

module Template
  def self.render(tree, total, count, zeros, dropped)
    tree_json = serialize_tree(tree).to_json
    "#{build_html(total, count, zeros, dropped, tree_json)}"
  end

  def self.serialize_tree(node)
    {
      name: node[:name],
      type: node[:type],
      pct: folder_pct(node),
      children: node[:children].transform_values { |child| serialize_tree(child) },
      modules: serialize_modules(node[:modules])
    }
  end

  def self.folder_pct(node)
    node[:type] == 'folder' ? compute_avg(node) : node[:pct]
  end

  def self.serialize_modules(modules)
    modules.map { |m| { name: m[:name], pct: m[:pct], type: 'module' } }
  end

  def self.compute_avg(node)
    all_mods = collect_all_modules(node)
    return 0.0 if all_mods.empty?

    average = sum_pcts(all_mods) / all_mods.length
    average.round(2)
  end

  def self.sum_pcts(mods)
    mods.map { |m| m[:pct] }.sum.to_f
  end

  def self.collect_all_modules(node)
    mods = node[:modules].dup
    node[:children].values.each { |child| mods.concat(collect_all_modules(child)) }
    mods
  end

  def self.build_html(total, count, zeros, dropped, tree_json)
    color = color_for(total)
    total_fmt = format('%.2f', total)

    <<~HTML
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Coverage Report</title>
        <style>#{Styles::RULES}</style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>Coverage Report</h1>
            <div class="summary-row">
              #{summary_tiles(color, total_fmt, count, zeros, dropped)}
            </div>
          </div>
          <div class="content">
            <div id="breadcrumb" class="breadcrumb"></div>
            <div class="controls">
              <button onclick="app.root()">Root</button>
            </div>
            <div id="browser" class="browser"></div>
            <div class="footer">
              Coverage report generated by mix cover
            </div>
          </div>
        </div>

        <script id="tree-data" type="application/json">
          #{tree_json}
        </script>

        <script>
          #{Client.app_script}
        </script>
      </body>
      </html>
    HTML
  end

  def self.summary_tiles(color, total_fmt, count, zeros, dropped)
    <<~HTML
      <div class="summary-item">
        <div class="summary-label">Total Coverage</div>
        <div class="summary-value" style="background-color: ##{color};">#{total_fmt}%</div>
      </div>
      <div class="summary-item">
        <div class="summary-label">Modules (with pages)</div>
        <div class="summary-count">#{count}</div>
      </div>
      <div class="summary-item">
        <div class="summary-label">No Coverage</div>
        <div class="summary-count" style="color: #e05d44;">#{zeros}</div>
      </div>
      <div class="summary-item">
        <div class="summary-label">Dropped (no pages)</div>
        <div class="summary-count" style="color: #999;">#{dropped}</div>
      </div>
    HTML
  end

  def self.color_for(pct)
    pct >= 80.0 ? '23D96C' : high_or_low(pct)
  end

  def self.high_or_low(pct)
    pct >= 50.0 ? 'dfb317' : 'e05d44'
  end
end
